# Generated by Django 4.2.7 on 2024-02-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_uz', '0002_company_district_experience_job_like_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='neighbour',
        ),
        migrations.AddField(
            model_name='region',
            name='neighbour',
            field=models.ManyToManyField(blank=True, null=True, related_name='children', to='hh_uz.region'),
        ),
    ]
