# Generated by Django 4.2.7 on 2024-02-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_uz', '0004_remove_job_district_job_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
