# Generated by Django 4.2.7 on 2024-02-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_uz', '0005_alter_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='typeOfWork',
            field=models.CharField(choices=[('OFF', 'offline'), ('ON', 'online')], default='OFF', max_length=7),
        ),
    ]
