# Generated by Django 4.2.7 on 2024-02-21 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hh_uz', '0006_job_typeofwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='hh_uz.profession'),
        ),
    ]
