# Generated by Django 4.2.7 on 2024-02-21 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hh_uz', '0007_alter_job_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='profession',
        ),
        migrations.AddField(
            model_name='job',
            name='profession_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='hh_uz.professiontype'),
            preserve_default=False,
        ),
    ]
