# Generated by Django 4.2.7 on 2024-02-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_uz', '0008_remove_job_profession_job_profession_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='career',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
