# Generated by Django 4.2.7 on 2024-02-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_uz', '0009_job_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workingTime',
            field=models.CharField(choices=[('FULL', 'Full time'), ('HALF', 'Half day')], default='FULL', max_length=7),
        ),
    ]
